//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalEngine.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffQualification
    {
        public int ID { get; set; }
        public string Qualification { get; set; }
        public string School { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> StaffID { get; set; }
    }
}
